# 5.16 List 2 Dimensi
List 2 dimensi pada umumnya adalah menempatkan sebuah list di dalam list.

In [1]:
#Latihan List 2 Dimensi 1

matrik = [
    #selalu awali list dengan [ yang mengartikan bentuk program ini adalah list
    [1,2,3],     #baris ke 0
    [3,2,3],
    [1,3,2],
]
#dan selalu akhiri dengan ] yang mengartikan list selesai
print (matrik)

#untuk baris adalah urutan mendatar
#untuk kolom adalah urutan menurun
#baris dan kolom dimulai dari 0

[[1, 2, 3], [3, 2, 3], [1, 3, 2]]


In [2]:
#Latihan List 2 Dimensi 2

matrik[1]

#pemanggilan baris urutan ke-yang diinginkan

[3, 2, 3]

In [3]:
#Latihan List 2 Dimensi 3

matrik[1][2] 

#merupakan pemanggilan angka pada baris ke-1 dan kolom ke-2

3

In [4]:
#Latihan List 2 Dimensi 4

matrik[1][2]=100    
print(matrik[1][2])
print(matrik)

#merupakan penggantian matrik pada baris ke-1 dan kolom ke-2 dengan 100

100
[[1, 2, 3], [3, 2, 100], [1, 3, 2]]


In [5]:
#Latihan List 2 Dimensi 5

matrik

#pemanggilan list matrik

[[1, 2, 3], [3, 2, 100], [1, 3, 2]]

In [6]:
#Latihan List 2 Dimensi 6

for baris in matrik:
    print(baris)
    for kolom in baris:
        print(kolom)
        
#pemanggilan list pada matrik dapat dilakukan dengan for yaitu dengan sebagai berikut
#dengan begitu list baris dan kolom pada matrik dapat diketahui

[1, 2, 3]
1
2
3
[3, 2, 100]
3
2
100
[1, 3, 2]
1
3
2


In [7]:
for a in matrik:
    print(a)
    
#variabel a dipakai untuk menyimpan isi dari element yang saat ini sedang diproses.
#Nama variabel a sendiri boleh bebas, fungsinya hanya sebagai variabel bantu saja

#Dalam format ini, kita mendefinisikan variabel matrik sebagai sebuah array atau himpunan 
#Perulangan for akan dijalankan sebanyak jumlah elemen yang ada di dalam variabel matrik.

[1, 2, 3]
[3, 2, 100]
[1, 3, 2]


# 5.17 Tuples
Tuples mirip dengan list, akan tetapi tuples tidak dapat dirubah isinya. Jika kita memeiliki data yang tidak ingin dirubah isisnya, kita gunakan tupkes, sedangkan jika datanya masih ingin dimanipulasi kedepannya, gunakan list.

In [8]:
angka = (6,7,4,5,8,9)

#hal ini sama seperti diketahui
#urutannya sama dengan yang lain, yaitu dimulai dari 0

In [9]:
#Latihan Tuples 1

print (angka[0])

#hal tersebut berarti pemanggilan list pada urutan ke- yang diinginkan

6


In [10]:
#Latihan Tuples 2

print(angka[0:3])

#[x,y] hal tersebut merupakan pemanggilan list dari urutan dari-x ke-y
#yang urutannya dimulai dari 0

(6, 7, 4)


In [11]:
#Latihan Tuples 3

for isi in angka[0:3]:
    print (isi)
    
#dapat dilakukan dengan mnggunakan for, akan tetapi outputnya adalah urutan list yang menurun

6
7
4


In [12]:
#Latihan Tuples 4

angka[0] = 10

#Program ini tidak bisa menjalankan perintah karena tuples tidak bisa direplace
#sesuai dengan definisi, jika ingin menggunakan Tuples apabila kita memiliki data yang tidak inggin dirubah, jika ingin dirubah maka menggunakan list

TypeError: 'tuple' object does not support item assignment

In [13]:
#Latihan Tuples 5

angka.append(10)

#Append sebenarnya berfungsi untuk menambahkan anggota terakhir pada sebuah list
#Mengingat ini bukanlah list melainkan Tuples, maka 'append' tidak bisa bekerja pada program ini

AttributeError: 'tuple' object has no attribute 'append'

In [14]:
#Latihan Tuples 6

angka.remove(10)

#Remove pada program ini sebenarnya berfungsi untuk menghapus elemen '10' pada sebuah list
#Namun, karena program ini merupakan Tuples, maka perintah remove tidak bisa dijalankan 

AttributeError: 'tuple' object has no attribute 'remove'

In [15]:
#Latihan Tuples 7

angka.count(1)

#Count pada program ini berfungsi untuk menghitung jumlah angka 1 pada tuples 'angka'
#Tidak adaa angka 1 pada Tuples 'angka'
#Maka hasil dari program ini adalah 0

0

In [16]:
#Latihan Tuples 8

angka.index(4)

#Fungsi index pada program ini adalah untuk mengetahui posisi elemen, pada kasus ini adalah elemen 4
#Elemen angka 4 terletak pada urutan ke 2 dalam list 'angka'
#Jadi hasil dari program ini adalah 2

2

In [17]:
#Latihan Tuples 8

tup1 = (3,) 
print(tup1[0])

#Jika elemen tuple hanya ada 1 elemen saja, tetap harus menuliskan ',' karena jika tidak program tidak dapat dijalankan

3


In [18]:
#Latihan Tuples 9

tup1 = (3, 5.6)
tup2 = ('fgh', 'xyz')
tup3 = tup1 + tup2
print (tup3)

#Karena elemen pada tuples tidak bisa ditambahkan, maka bisa dengan menggabungkan antara elemen 1 dan elemen 2 
#Kemudian kita mencetak elemen baru yang merupakangabungan dari 2 elemen sebelumnya 

(3, 5.6, 'fgh', 'xyz')


# Tambahan

In [19]:
import numpy as np
d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(d)

#kita dapat melakukan rumus numpy dengan di awal 

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [20]:
for baris in matrik:
    print(baris)
for kolom in baris:
    print(kolom)
        
#hal ini berbeda dengan Latihan list 2 dimensi 6 karena didahulukan untuk for baris sehingga list bernilai false
#kemudian output dari for kolom akan keluar hingga nilai for untuk kolom bernilai false

[1, 2, 3]
[3, 2, 100]
[1, 3, 2]
1
3
2


# 5.18 Dictionaries
Dictionaries digunakan jika data nya terkait satu sama lain. Misalnya data
seseorang yang terdiri dari umur, nama, tanggal lahir merupakan satu kesatuan
data yang bersumber dari orang tersebut.

In [21]:
#Latihan Dictionaries 1

data_mahasiswa = {
    #selalu awali dengan {
    "nama" : "aulia sari",  #setiap nilai dipisahkan tanda koma
    #Karena kumpulan nilai di dictionary menggunakan key dan value, maka setiap key dipisahkan dari value-nya dengan tanda titik dua ":"
    "nim"  : "034",         
    "apakah_lulus" : True
}
#dan selalu diakhiri dengan } yang berarti program selesai

In [22]:
#Latihan Dictionaries 2

print(data_mahasiswa['nama'])

#hal ini berarti pemanggilan nama dari data_mahasiswa
#dan selalu dengan penggunaan huruf kapital dan ejaan yang sesuai, dengan hal itu program bernilai true dan dapat dijalankan

aulia sari


In [23]:
#latihan Dictionaries 3

print(data_mahasiswa['Nama'])

#hal ini berarti pemanggilan Nama dari data_mahasiswa
#dan selalu dengan penggunaan huruf kapital dan ejaan yang sesuai, dengan hal itu program bernilai true dan dapat dijalankan
#jika kita memanggil hal sesuatu dengan huruf dan ejaan yang salah, maka program tidak dapat dijalankan karena program bernilai false

KeyError: 'Nama'

In [24]:
#latihan Dictionaries 4

print(data_mahasiswa.get('nama'))

#Program ini sebenarnya berfungsi sama seperti Latihan 1, namun yang membedakan adalah penggunaan 'get'
#Kalau menggunakan get pakai (), sedangkan kalau tidak pakai menggunakan []
#dan selalu dengan penggunaan huruf kapital dan ejaan yang sesuai, dengan hal itu program bernilai true dan dapat dijalankan

aulia sari


In [25]:
#latihan Dictionaries 5

print(data_mahasiswa.get('Nama'))

#Program ini sebenarnya berfungsi sama seperti Latihan 1, namun yang membedakan adalah penggunaan 'get'
#Kalau menggunakan get pakai (), sedangkan kalau tidak pakai menggunakan []
#dan selalu dengan penggunaan huruf kapital dan ejaan yang sesuai, dengan hal itu program bernilai true dan dapat dijalankan
#jika kita memanggil hal sesuatu dengan huruf dan ejaan yang salah, maka output outputnya adalah None

None


In [26]:
#latihan Dictionaries 6

print(data_mahasiswa.get('tanggal_lahir'))

#tidak ditemukan karena memang tidak dicantumkan 

None


In [27]:
#latihan Dictionaries 7

print(data_mahasiswa.get('tanggal_lahir','1-1-2005'))

#Program ini adalah untuk menambahkan data yang tidak didefinisikan

1-1-2005


In [28]:
#latihan Dictionaries 8

print(data_mahasiswa)

#Pada program ini dibuktikan bahwa 'tanggal_lahir' yang sudah ditambahkan pada latihan Dictionaries 7 tidak permanen

{'nama': 'aulia sari', 'nim': '034', 'apakah_lulus': True}


In [29]:
#latihan Dictionaries 9

print(data_mahasiswa["tanggal_lahir"])

#Jika kita menggunakan kurung siku [], apabila definisi tidak ditemukan, dia tidak akan mengeluarkan hasil 'None', melainkan error

KeyError: 'tanggal_lahir'

In [30]:
#latihan Dictionaries 10

data_mahasiswa['instagram'] = 'aauliasari_'

#Memasukkan data baru pada 'data_mahasiswa'

In [31]:
#latihan Dictionaries 11

print(data_mahasiswa["instagram"])

aauliasari_


In [32]:
#latihan Dictionaries 12

print(data_mahasiswa)

#Dengan menggunakan program seperti ini, data akan berubah secara permanen
#Sekarang, 'data_mahasiswa' akan berisi nama, umur, apakah_lulus, dan instagram

{'nama': 'aulia sari', 'nim': '034', 'apakah_lulus': True, 'instagram': 'aauliasari_'}


In [33]:
#latihan Dictionaries
#buatlah program untuk merubah nomor HP yang tadinya angka menjadi sebutan bilangan tersebut. misalnya angka 0812 menjadi nol delapan satu dua
#Jawaban
angka ={
    "0" : "nol",
    "1" : "satu",
    "2" : "dua",
    "3" : "tiga",
    "4" : "empat",
    "5" : "lima",
    "6" : "enam",
    "7" : "tujuh",
    "8" : "delapan",
    "9" : "sembilan"
}

In [35]:
nomor_HP = input("Masukan nomor HP anda ")
nomor_angka = ""
for isi in nomor_HP:
    nomor_angka += angka.get(isi) + " "
print(nomor_angka)

Masukan nomor HP anda 08123456789
nol delapan satu dua tiga empat lima enam tujuh delapan sembilan 


# 5.19 Fungsi dalam Python
Sampai sejauh ini tanpa disadari kita telah menerapkan beberapa jenis fungsi
pada Python seperti fungsi input, print, len, range, dll. Pada dasarnya fungsi
dibentuk untuk menghidari pengulangan pembuatan program secara manual
dimana fungsi tersebut memiliki pengulangan yang tinggi dalam program yang
kita buat. Jadi untuk mempermudah dan meringkas program yang kita buat,
setiap fungsi tersebut dibutuhkan tinggal kita panggil.

In [38]:
def full_nama(first_name,last_name):
    print(f"Nama lengkapnya adalah {first_name} {last_name}")

In [39]:
first_name = input("Nama depan anda adalah ")
last_name = input("Nama belakang anda adalah ")
full_nama(first_name,last_name)

Nama depan anda adalah aulia
Nama belakang anda adalah sari
Nama lengkapnya adalah aulia sari


# 5.19.1 Tugas Fungsi pada Python

In [40]:
def waktu_sampai(jarak,kecepatan):
    waktu = jarak/kecepatan
    print(waktu)

In [41]:
def waktu_tempuh(jarak,kecepatan):
    waktu = jarak/kecepatan
    return waktu

In [42]:
waktu_sampai(80,60)

1.3333333333333333


In [43]:
waktu_tempuh(80,60)

1.3333333333333333

In [44]:
a = waktu_sampai(80,60)
print(a)

1.3333333333333333
None


In [45]:
b = waktu_tempuh(80,60)
print(b)

1.3333333333333333


In [46]:
#Latihan : buatlah program yang menggunakan fungsi Python untuk menghitung luas segitiga, lingkaran, persegi dan persegi panjang. selain itu berikan peringatan bagi bidang lain yang tidak termasuk perhitungan.
#Jawaban

import numpy as np

def luas_segitiga(alas,tinggi):
    luas = (1/2)*alas*tinggi
    return luas
def luas_lingkaran(jari_jari):
    luas = np.pi*(jari_jari)**2
    return luas
def luar_persegi(sisi) :
    luas = (sisi)**2
    return luas
def luas_persegi_panjang(panjang,lebar):
    luas = panjang*lebar
    return luas

In [47]:
jenis_bidang = input("Tulis jenis bidangnya ")
if jenis_bidang.upper() == 'SEGITIGA':
    alas = float(input('Berapakah panjang alasnya? '))
    tinggi =float(input('Berapakah tingginya? '))
    luas = luas_segitiga(alas,tinggi)
    print(f"Luas {jenis_bidang} adalah {luas}")
elif jenis_bidang.upper() == 'LINGKARAN':
    jari_jari = float(input('Berapakah panjang jari-jarinya? '))
    luas = luas_lingkaran(jari_jari)
    print(f"Luas {jenis_bidang} adalah {luas}")
elif jenis_bidang.upper() == 'PERSEGI':
    sisi = float(input('Berapakah panjang sisinya? '))
    luas = luas_persegi(sisi)
    print(f"Luas {jenis_bidang} adalah {luas}")
elif jenis_bidang.upper() == 'PERSEGI PANJANG':
    panjang = float(input('Berapakah panjangnya? '))
    lebar =float(input('Berapakah lebarnya? '))
    luas = luas_persegi_panjang(alas,tinggi)
    print(f"Luas {jenis_bidang} adalah {luas}")
else:
    print(f"Maaf bidang {jenis_bidang} yang anda masukkan tidak ada.")
    print("Pilihan cuma SEGITIGA, LINGKARAN, PERSEGI, dan PERSEGI PANJANG.")
    print('Terimakasih')

Tulis jenis bidangnya SEGITIGA
Berapakah panjang alasnya? 36
Berapakah tingginya? 6
Luas SEGITIGA adalah 108.0


# 5.20 Numpy
Numpy merupakan salah satu Library dalam Python yang memiliki keunggulan
dalam perhitungan menggunakan vektor dam matrik dalam berbagai dimensi.

In [48]:
#Hal pertama yang perlu dilakukan adalah memanggil Library Numpy sebagai berikut

import pandas as pd
import numpy as np

# 5.20.1 Perintah Dasar pada Numpy


In [49]:
import numpy as np
#Pastikan untuk menuliskan perintah ini untuk memanggil library numpy
a = np.array([1,2,3,4])
print(a)

#output yang akan keluar sama seperti list

[1 2 3 4]


In [50]:
import numpy as np
b = np.array([[5,6,7,8],[9,8,7,6],[7,8,9,6]])
print(b)

#Apabila kita membuat 2 atau lebih array, maka akan dicetak secara vertikal

[[5 6 7 8]
 [9 8 7 6]
 [7 8 9 6]]


In [51]:
a.ndim

#Fungsi ndim adalah untuk mengetahui jumlah dimensi array Numpy

1

In [52]:
b.ndim

#Dimensi pada b adalah 2

2

In [53]:
a.shape

#Pada fungsi shape menghasilkan sebuah tuple yang berisikan panjang sebuah array pada tiap dimensi.
#Array d memiliki shape 4, yaitu panjang array pada 1-dimensi array.

(4,)

In [54]:
b.shape

#Array c memiliki shape 4, yaitu panjang array pada 3-dimensi array.

(3, 4)

# 5.20.2 Memanggil Anggota, Kolom dan Baris dengan Numpy


In [55]:
import numpy as np
d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [56]:
d[0,2]
#[0,2], 0 melambangkan indeks ke 0 dari 2 indeks yang tersedia, indeks pertama dihitung 0
#2 melambangkan elemen ke 2  dari indeks ke 0, karena dimulai dari 0 

3

In [57]:
d[1,:]

#Kode ini memuat perintah untuk mencetak indeks ke 1
#Karena tidak dituliskan elemen ke berapa dari indeks yang ingin dicetak, maka semua elemen dicetak

array([5, 6, 7, 8])

In [58]:
d[:,2]

#Kode ini memuat perintah untuk mencetak elemen ke 2 pada semua indeks

array([ 3,  7, 11])

In [59]:
d[0,1:2]

#Kode ini untuk mencetak indeks ke 0
#[1:2] artinya yaitu cetak elemen ke 1 sampai 2

array([2])

In [60]:
d[0,0:1:2]

#Program ini untuk mencetak indeks ke 0
#Elemen dari indeks ke 0 ini dicetak dari elemen ke 0 sampai sebelum elemen ke 2 
#Dengan loncatan sebanyak 2 kali

array([1])

In [61]:
d[0,0] =  50
print(d)

#Program ini adalah untuk mengganti indeks ke 0 dan elemen ke 0 dengan angka 50

[[50  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


# 5.20.3 Matrix pada Numpy

In [62]:
np.ones((2,3))
#Mencetak matrix 2x3 dengan elemennya adalah 1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [63]:
np.zeros((2,2))
#Mencetak matrix 2x2 dengan elemennya adalah 0

array([[0., 0.],
       [0., 0.]])

In [64]:
np.identity(6)
#Mencetak matrix identitas dengan ukuran 6x6

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [65]:
np.ones((7,3,4))
#Mencetak 7 buah matrix ukuran 3x4 dengan 1 sebagai semua elemennya

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [66]:
np.full((3,2),9)
#Untuk mencetak matrix berukuran 3x2 dengan 9 sebagai semua elemennya

array([[9, 9],
       [9, 9],
       [9, 9]])

In [67]:
np.random.rand(4,3)
#Untuk mencetak matrix berukuran 4x3 
#Metode rand() pada modul random mengembalikan float acak antara 0 dan 1.

array([[0.92070586, 0.22646186, 0.27129385],
       [0.04980346, 0.38593586, 0.73047107],
       [0.92137627, 0.71924062, 0.86988728],
       [0.02767785, 0.30127809, 0.18828439]])

In [68]:
np.random.randint(1,10,size=(3,4))
#Mencetak matrix ukuran 3x4 dengan elemen-elemennya terdiri dari bilangan 1 sampai 10

array([[3, 4, 6, 3],
       [6, 2, 5, 5],
       [6, 3, 4, 8]])

In [69]:
a = np.zeros((10,10))
print(a)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [70]:
b=np.identity(9)
print(b)

[[1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [71]:
c=8*b
print(c)

[[8. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 8. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 8. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 8. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 8. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 8. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 8. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 8. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 8.]]


In [72]:
d=np.ones((8,8))
e=np.identity(8)*8
f=d+e
print(f)

[[9. 1. 1. 1. 1. 1. 1. 1.]
 [1. 9. 1. 1. 1. 1. 1. 1.]
 [1. 1. 9. 1. 1. 1. 1. 1.]
 [1. 1. 1. 9. 1. 1. 1. 1.]
 [1. 1. 1. 1. 9. 1. 1. 1.]
 [1. 1. 1. 1. 1. 9. 1. 1.]
 [1. 1. 1. 1. 1. 1. 9. 1.]
 [1. 1. 1. 1. 1. 1. 1. 9.]]


In [73]:
c[1:-1,1:-1] = f
print(c)

ValueError: could not broadcast input array from shape (8,8) into shape (7,7)

In [74]:
g = np.identity(6)*9
c[2:-2,2:-2] = g
print(c)

ValueError: could not broadcast input array from shape (6,6) into shape (5,5)

In [75]:
h = np.ones((4,4))*2
i = np.identity(4)=7
j = h+i
print(j)

SyntaxError: cannot assign to function call (3758992802.py, line 2)

In [76]:
c[3:-3,3:-3] = j
print(c)

NameError: name 'j' is not defined

In [77]:
k = np.identity(2)*9
c[4:-4,4:-4] = k
print(c)

ValueError: could not broadcast input array from shape (2,2) into shape (1,1)

# 5.20.4 Copy pada Numpy

In [78]:
a= np.array([1,2,3,4,5])
print(a)

#Program ini adalah untuk mencetak anggota dari array a yaitu 1,2,3,4,5

[1 2 3 4 5]


In [79]:
b = a
print(b)

#Program ini adalah untuk membuat elemen dari array b adalah sama persis dengan array a

[1 2 3 4 5]


In [80]:
b[0] = 10
print(b)

#urutan dimulai dari 0
#Program ini adalah untuk mengganti elemen ke 0 yang tadinya adalah angka 1 menjadi angka 10

[10  2  3  4  5]


In [81]:
print(a)

#Karena tadi kita sudah mengganti elemen ke 0 dengan 10, jadi elemen dari array a menjadi 10,2,3,4,5

[10  2  3  4  5]


In [82]:
c = np.array([1,2,3,4,5])


#Kita definisikan array c dengan elemennya adalah 1,2,3,4,5

In [83]:
d = c.copy()
print(d)

#Terdapat cara lain untuk mengcopy sebuah array supaya identik dengan array yang baru
#Contohnya adalah cara ini

[1 2 3 4 5]


In [84]:
d[0] = 30
print(d)

#Karena kita mengganti elemen ke 0 pada array d

[30  2  3  4  5]


In [85]:
print(c)

#Karena kita tidak pernah merubah elemen dari array c, maka elemen-elemen dari array c tetap sama 

[1 2 3 4 5]


# 5.20.5 Operasi Matematika pada Numpy

In [86]:
a = np.array([5,6,7,8,9])

In [87]:
a+4

#Program ini memerintahkan setiap elemen dari array a dijumlahkan 4

array([ 9, 10, 11, 12, 13])

In [88]:
a-6

#Program ini memerintahkan bahwa setiap elemen dari a harus dikurangi dengan 6

array([-1,  0,  1,  2,  3])

In [89]:
a*2

#Program ini memerintahkan bahwa setiap elemen dari a harus dikalikan dengan 2

array([10, 12, 14, 16, 18])

In [90]:
a/2

#Program ini untuk memuat perintah bahwa setiap elemen dari array a harus dibagi dengan 2

array([2.5, 3. , 3.5, 4. , 4.5])

In [91]:
a**2

#Program ini adalah untuk memuat perintah bahwa setiap elemen dari array a harus dipangkatkan 2

array([25, 36, 49, 64, 81], dtype=int32)

In [92]:
b = np.array([6,7,8,9,10,11,12,13])
#Kita mempunyai array baru yaitu array b dengan elemennya adalah 6,7,8,9,10
#Baik nama array ataupun elemen array adalah bebas 

In [93]:
a+b

ValueError: operands could not be broadcast together with shapes (5,) (8,) 

In [94]:
a-b
#Namun pada operasi pengurangan, elemen array yang berbeda jumlah tidak dapat diproses

ValueError: operands could not be broadcast together with shapes (5,) (8,) 

In [95]:
a/b
#Operasi pembagian masih bisa dijalankan walaupun jumlah elemen array berbeda 

ValueError: operands could not be broadcast together with shapes (5,) (8,) 

In [96]:
b**a

ValueError: operands could not be broadcast together with shapes (8,) (5,) 

In [97]:
a = np.array([5,6,7,8,9])
b = np.array([6,7,8,9,10])

In [98]:
a-b

array([-1, -1, -1, -1, -1])

In [99]:
a*b

array([30, 42, 56, 72, 90])

In [100]:
np.cos(a)

array([ 0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026])

In [101]:
np.cos(b)

array([ 0.96017029,  0.75390225, -0.14550003, -0.91113026, -0.83907153])

In [102]:
np.tan(a)

array([-3.38051501, -0.29100619,  0.87144798, -6.79971146, -0.45231566])

In [103]:
np.sinh(a)

array([  74.20321058,  201.71315737,  548.31612327, 1490.47882579,
       4051.54190208])

In [104]:
np.cosh(a)

array([  74.20994852,  201.71563612,  548.31703516, 1490.47916125,
       4051.54202549])

In [105]:
np.tanh(a)

array([0.9999092 , 0.99998771, 0.99999834, 0.99999977, 0.99999997])

In [106]:
np.sqrt(a)

array([2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

# 5.20.6 Perkalian Matrix pada Numpy


In [107]:
a = np.array ([[1,2,3,4],[5,6,7,8]])
print(a)


[[1 2 3 4]
 [5 6 7 8]]


In [108]:
b = np.array ([[9,8,7,6],[7,1,4,3]])
print(b)

[[9 8 7 6]
 [7 1 4 3]]


In [109]:
c = a*b
print(c)

[[ 9 16 21 24]
 [35  6 28 24]]


In [110]:
d = np.matmul(a,b)
print(d)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 4)

In [111]:
e = np.array([[9,10],[11,12],[13,14],[15,16]])
print(e)


[[ 9 10]
 [11 12]
 [13 14]
 [15 16]]


In [112]:
f = np.matmul(a,e)
print(f)

[[130 140]
 [322 348]]


In [113]:
g = a*e

ValueError: operands could not be broadcast together with shapes (2,4) (4,2) 

# 5.20.7 min, max, dan sum pada Numpy

In [114]:
a = np.array([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [115]:
b = np.min(a)
print(b)

1


In [116]:
d = np.min(a,axis=1)
print(d)


[1 5 9]


In [117]:
e = np.max(a)
print(e)


12


In [118]:
g = np.max(a,axis=1)
print(g)

[ 4  8 12]


In [119]:
h = np.sum(a)
print(h)

78


In [120]:
h = np.sum(a,axis=0)
print(h)


[15 18 21 24]


In [121]:
i = np.sum(a,axis=1)
print(i)

[10 26 42]
